# Generated by Django 6.0 on 2025-12-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='current_profile',
            new_name='current_profile_id',
        ),
    ]
