# Generated by Django 6.0 on 2025-12-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_profile',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
