# Generated by Django 6.0 on 2025-12-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_options_alter_account_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
