# Generated by Django 6.0 on 2025-12-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_owner_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_profile',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
