# Generated by Django 6.0 on 2025-12-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0002_alter_entry_created_alter_topic_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('DRAFT', 'draft'), ('TRASH', 'trash')], default='ACTIVE', max_length=6),
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('DRAFT', 'draft'), ('TRASH', 'trash')], default='ACTIVE', max_length=6),
        ),
    ]
