# Generated by Django 6.0 on 2025-12-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0003_entry_status_topic_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('topics', models.ManyToManyField(to='notepad.topic')),
            ],
        ),
    ]
