# Generated by Django 6.0 on 2025-12-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0004_topiccategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccategory',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='categories', related_query_name='category', to='notepad.topic'),
        ),
    ]
