# Generated by Django 6.0 on 2025-12-29 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0005_alter_topiccategory_topics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicCategory',
        ),
    ]
